# Generated by Django 2.2.9 on 2020-01-31 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inte_screening", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsubjectscreening",
            name="clinic_type",
            field=models.CharField(
                choices=[("ncd_clinic", "NCD Clinic"), ("hiv_clinic", "HIV Clinic")],
                default="hiv_clinic",
                max_length=25,
                verbose_name="Form which type of clinic was the patient selected",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subjectscreening",
            name="clinic_type",
            field=models.CharField(
                choices=[("ncd_clinic", "NCD Clinic"), ("hiv_clinic", "HIV Clinic")],
                default="hiv_clinic",
                max_length=25,
                verbose_name="Form which type of clinic was the patient selected",
            ),
            preserve_default=False,
        ),
    ]
